name: Publish Specified Package

on:
  workflow_dispatch:
    inputs:
      myInput:
        description: 'Enter the package path'     
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Hello, ${{ github.event.inputs.myInput }}"